# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MockProject' do
use_frameworks!
target 'Your target name'
pod 'KeychainSwift', '~> 16.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MockProject

end
